services:

  postgres:
    image: postgres:17
    container_name: mecanica-db
    environment:
      POSTGRES_DB: mecanica
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234567
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mecanica"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  app:
    build: .
    container_name: mecanica-api
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mecanica
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234567
      JWT_SECRET: Ie+o8U7OfpdBdhHUp9mQ+U/8ayI20O2Tp1+35tR2jabK4n2w4BreTofRsQDqzl9aUVpt2nu0azdv3tPWZkROZA==
      EMAIL_NOTIFICATIONS_ENABLED: "true"
      EMAIL_FROM: no-reply@mecanica.local
      SPRING_MAIL_HOST: mailhog
      SPRING_MAIL_PORT: 1025
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "false"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "false"

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: mecanica-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  sonarqube-db:
    image: postgres:17
    container_name: sonarqube-db
    environment:
      POSTGRES_DB: sonarqube
      POSTGRES_USER: sonarqube
      POSTGRES_PASSWORD: sonarqube
    volumes:
      - sonarqube_db_data:/var/lib/postgresql/data

  sonarqube:
     image: sonarqube:community
     container_name: sonarqube
     depends_on:
       - sonarqube-db
     ports:
       - "9000:9000"
     environment:
       SONAR_JDBC_URL: jdbc:postgresql://sonarqube-db:5432/sonarqube
       SONAR_JDBC_USERNAME: sonarqube
       SONAR_JDBC_PASSWORD: sonarqube
     volumes:
       - sonarqube_data:/opt/sonarqube/data
       - sonarqube_extensions:/opt/sonarqube/extensions
       - sonarqube_logs:/opt/sonarqube/logs

volumes:
  postgres_data:
  sonarqube_db_data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
