spring.application.name=fiap-soat-mecanica-api

#Banco de dados
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/mecanica}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

#JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
#logging.level.org.hibernate=DEBUG
#logging.level.org.hibernate.type=DEBUG

#FLYWAY
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

#CRIPTOGRAFIA
jwt.secret=${JWT_SECRET}

#ACTUATOR
management.endpoint.health.probes.enabled=true
management.endpoints.web.exposure.include=health

#NOTIFICACAO POR E-MAIL
app.notification.email.enabled=${EMAIL_NOTIFICATIONS_ENABLED:true}
app.notification.email.from=${EMAIL_FROM:no-reply@mecanica.local}

spring.mail.host=${SPRING_MAIL_HOST:localhost}
spring.mail.port=${SPRING_MAIL_PORT:1025}
spring.mail.default-encoding=UTF-8
spring.mail.username=${SPRING_MAIL_USERNAME:}
spring.mail.password=${SPRING_MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH:false}
spring.mail.properties.mail.smtp.starttls.enable=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE:false}
spring.mail.properties.mail.smtp.connectiontimeout=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_CONNECTIONTIMEOUT:5000}
spring.mail.properties.mail.smtp.timeout=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_TIMEOUT:5000}
spring.mail.properties.mail.smtp.writetimeout=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_WRITETIMEOUT:5000}
