spring.application.name=fiap-soat-mecanica-api

#Banco de dados
spring.datasource.url=jdbc:postgresql://localhost:5433/mecanica
spring.datasource.username=postgres
spring.datasource.password=1234567

#JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

#FLYWAY
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

#CRIPTOGRAFIA
jwt.secret=${JWT_SECRET}