apiVersion: apps/v1
kind: Deployment
metadata:
  name: mecanica-api
  namespace: ${namespace}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mecanica-api
  template:
    metadata:
      labels:
        app: mecanica-api
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: mecanica-api
          image: ${api_image}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          envFrom:
            - secretRef:
                name: mecanica-api-secret
            - configMapRef:
                name: mecanica-api-config
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            failureThreshold: 3
            periodSeconds: 10
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            failureThreshold: 6
            periodSeconds: 5
            timeoutSeconds: 3
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            failureThreshold: 30
            periodSeconds: 5
            timeoutSeconds: 3
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "768Mi"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
