apiVersion: v1
kind: Secret
metadata:
  name: mecanica-api-secret
data:
  SPRING_DATASOURCE_USERNAME: "cG9zdGdyZXM="
  SPRING_DATASOURCE_PASSWORD: "MTIzNDU2Nw=="
  JWT_SECRET: "SWUrbzhVN09mcGRCZGhIVXA5bVErVS84YXlJMjBPMlRwMSszNXRSMmphYks0bjJ3NEJyZVRvZlJzUURxemw5YVVWcHQybnUwYXpkdjN0UFdaa1JPWkE9PQ=="