apiVersion: v1
kind: Service
metadata:
  name: mecanica-db
  namespace: ${namespace}
spec:
  type: ClusterIP
  selector:
    app: mecanica-db
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
